---
title: "Work_Document"
format:
   html:
     toc: true
     html-math-method: katex
     embed-resources: true
     self-contained-math: true
     df-print: kable
editor: source
---

# Descargar Librerías

```{r}
library(tidyverse)
library(bnlearn)
```

# Abrir Datos
```{r}
data = read_csv("../data/data_preliminar.csv")
head(data)
```

# Proceso
## Crear DAGS
### Cambiar nombre  a Las columnas
Esto para referenciar de forma versátil a las variables seleccionadas
```{r}
colnames(data) = c("COL_HDL", "COL_LDL", "CREAT", "GLU_SUERO", "INSULINA", "PCR", "TRIG", "HB1AC", "SO_2","CO","NOx", "COV", "PM_010", "PM_2_5", "NH_3") #Mismo orden de las columnas 
head(data)
```

### DAG1
```{r}
dag1 = model2network("[SO_2][CO|SO_2][NOx|SO_2][COV|NOx][PM_010|CO:NOx][PM_2_5|CO:PM_010:SO_2][NH_3|COV:PM_010][COL_HDL][COL_LDL|COL_HDL][CREAT][GLU_SUERO][INSULINA][PCR][TRIG|COL_LDL][HB1AC|GLU_SUERO]")
```


```{r}
blood_fit1 = bn.fit(dag1, data=data)
```

#### Graficar
```{r}
graphviz.plot(dag1, shape = "ellipse")
```
#### Scores

```{r}
blood_fit1$TRIG
```

```{r}
score(dag1, data=data, type="bic-g")
```


```{r}
score(dag1, data=data, type="aic-g")
```

### DAG2


```{r}
dag2 <- model2network("[SO_2][CO][NOx][COV][PM_010][PM_2_5][NH_3][PCR|SO_2:CO:NOx:COV:PM_010:PM_2_5:NH_3][COL_HDL|PCR][COL_LDL|PCR][TRIG|COL_HDL:COL_LDL:PCR][CREAT|PCR][INSULINA|TRIG:PCR:CREAT][GLU_SUERO|INSULINA:TRIG:PCR][HB1AC|GLU_SUERO]")
```


```{r}
blood_fit2 = bn.fit(dag2, data=data)
```

#### Graficar

```{r}
graphviz.plot(dag2, shape = "ellipse")
```


```{r}
blood_fit2$TRIG
```

#### Scores
```{r}
score(dag2, data=data, type="bic-g")
```


```{r}
score(dag2, data=data, type="aic-g")
```

### DAG3

```{r}
dag3 = model2network("[SO_2][NOx][NH_3][CO][COV][PM_010|CO:COV][PM_2_5|SO_2:NOx:NH_3:PM_010][PCR|PM_2_5][INSULINA|PCR][GLU_SUERO|INSULINA][HB1AC|GLU_SUERO][TRIG|INSULINA][COL_LDL|TRIG][COL_HDL|TRIG][CREAT|GLU_SUERO]")
```


```{r}
blood_fit3 = bn.fit(dag3, data=data)
```

```{r}
graphviz.plot(dag3, shape = "ellipse")
```


```{r}
blood_fit3$TRIG
```

```{r}
score(dag3, data=data, type="bic-g")
```


```{r}
score(dag3, data=data, type="aic-g")
```


